service: order-pizza-service

frameworkVersion: '2'

provider:
  name: aws
  profile: personal
  region: eu-central-1
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

functions:
  create:
    handler: src/handlers/orders/create.create
    events:
      - http:
          method: POST
          path: /order

plugins:
  - serverless-ruby-layer

custom:
  rubyLayer:
    include_functions:
      - create
