service: aws-ruby-serverless-workshop

frameworkVersion: '2'

provider:
  name: aws
  profile: personal
  region: eu-central-1
  runtime: ruby2.7
  lambdaHashingVersion: 20201221

functions:
  hello:
    handler: handler.hello

plugins:
  - serverless-ruby-layer
