service: order-pizza-service

frameworkVersion: '2'

provider:
  name: aws
  profile: personal
  region: eu-central-1
  runtime: ruby2.7
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:Scan
      Resource:
        - arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/OrdersTable
functions:
  create:
    handler: src/handlers/orders/create.create
    events:
      - http:
          method: POST
          path: /order
  get:
    handler: src/handlers/orders/get.get
    events:
      - http:
          method: GET
          path: /orders

resources:
  Resources:
    OrdersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: OrdersTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

plugins:
  - serverless-ruby-layer
  - serverless-pseudo-parameters

custom:
  rubyLayer:
    include_functions:
      - create
      - get
